dist: trusty
matrix:
  include:
    - language: python
      python:
        - 3.6
      cache: pip
      install:
        - pip install -r python/requirements.txt
      before_script:
        - cd python
      script:
        - python -m pytest -s tests/
notifications:
    email: false