dist: trusty
matrix:
  include:
    - language: python
      python:
        - 3.6
      cache: pip
      install:
        - pip install -r python/requirements.txt
      before_script:
        - cd python
      script:
        - python -m pytest -s tests/
        - cd ..
        - bash .travis/deploy_dockerhub.sh test
      services:
        - docker
      deploy:
        # deploy to the develop environment
        - provider: script
          script:
            - bash .travis/deploy_dockerhub.sh develop push
          on:
            branch: develop
        # deploy to the staging environment
        - provider: script
          script: 
            - bash .travis/deploy_dockerhub.sh staging push
          on:
            branch: staging
        # deploy master to production
        - provider: script
          script: 
            - bash .travis/deploy_dockerhub.sh production push
          on:
            branch: master
notifications:
    email: false