dist: trusty
matrix:
  include:
    - language: python
      services:
        - docker
      python:
        - 3.6
      cache: pip
      install:
        - pip install -r python/requirements.txt
      before_script:
        - cd python
      script:
        - python -m pytest -s tests/
      after_success:
        - cd ..
        - bash .travis/deploy_dockerhub.sh test push
      deploy:
        # deploy develop to the staging environment
        - provider: script
          script:
            - bash .travis/deploy_dockerhub.sh staging
          on:
            branch: develop
        # deploy master to production
        - provider: script
          script: 
            - bash .travis/deploy_dockerhub.sh production
          on:
            branch: master
notifications:
    email: false